//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAIAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderService
    {
        public int Id { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<int> Service { get; set; }
    
        public virtual Order Order1 { get; set; }
        public virtual Service Service1 { get; set; }
    }
}
